# Site settings
title: Kahoks
header-img: img/home-bg.jpg
email: cweckmanl@cusd.kahoks.org
copyright_name: Clark Weckmann
description: "The official github for the CHS Kahoks!"
baseurl: "/blog"
url: ""
twitter_username: SBootstrap
github_username:  clarkhacks
facebook_username:  StartBootstrap
email_username:  cweckmanl@cusd.kahoks.org

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
